// Supabase Configuration
const SUPABASE_URL = 'https://qguwiwaltreecrbquoti.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFndXdpd2FsdHJlZWNyYnF1b3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NTQwNjEsImV4cCI6MjA1MDQzMDA2MX0.fFsZnqY-Prz8NYL55dhSY7AIl-FAlApvoZnwSbn8iMc';